apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-app-data
  namespace: rag-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi