# UPDATE THESE VALUES BEFORE DEPLOYING
# See SETUP_GUIDE.md for instructions on getting these values

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rag-app-secrets
  namespace: rag-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    # Get this value from: az aks show --resource-group YOUR-RG --name YOUR-AKS-CLUSTER --query "identityProfile.kubeletidentity.clientId" -o tsv
    userAssignedIdentityID: "YOUR-KUBELET-IDENTITY-CLIENT-ID"
    # Your Azure Key Vault name (e.g., my-rag-kv-123456)
    keyvaultName: "YOUR-KEYVAULT-NAME"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: google-service-account-email
          objectType: secret
          objectAlias: GOOGLE_CLIENT_EMAIL
        - |
          objectName: google-private-key
          objectType: secret
          objectAlias: GOOGLE_PRIVATE_KEY
        - |
          objectName: google-project-id
          objectType: secret
          objectAlias: GOOGLE_PROJECT_ID
        - |
          objectName: google-client-id
          objectType: secret
          objectAlias: GOOGLE_CLIENT_ID
        - |
          objectName: google-private-key-id
          objectType: secret
          objectAlias: GOOGLE_PRIVATE_KEY_ID
        - |
          objectName: google-drive-folder-id
          objectType: secret
          objectAlias: GOOGLE_DRIVE_FOLDER_ID
        - |
          objectName: azure-openai-api-key
          objectType: secret
          objectAlias: AZURE_OPENAI_API_KEY
        - |
          objectName: azure-openai-endpoint
          objectType: secret
          objectAlias: AZURE_OPENAI_ENDPOINT
        - |
          objectName: azure-openai-deployment-name
          objectType: secret
          objectAlias: AZURE_OPENAI_DEPLOYMENT_NAME
        - |
          objectName: azure-openai-embedding-deployment
          objectType: secret
          objectAlias: AZURE_OPENAI_EMBEDDING_DEPLOYMENT
        - |
          objectName: azure-search-endpoint
          objectType: secret
          objectAlias: AZURE_SEARCH_ENDPOINT
        - |
          objectName: azure-search-api-key
          objectType: secret
          objectAlias: AZURE_SEARCH_API_KEY
        - |
          objectName: azure-search-index-name
          objectType: secret
          objectAlias: AZURE_SEARCH_INDEX_NAME
        - |
          objectName: gemini-api-key
          objectType: secret
          objectAlias: GEMINI_API_KEY
        - |
          objectName: gemini-model
          objectType: secret
          objectAlias: GEMINI_MODEL
        - |
          objectName: azure-doc-intelligence-endpoint
          objectType: secret
          objectAlias: AZURE_DOC_INTELLIGENCE_ENDPOINT
        - |
          objectName: azure-doc-intelligence-key
          objectType: secret
          objectAlias: AZURE_DOC_INTELLIGENCE_KEY
        - |
          objectName: azure-translator-endpoint
          objectType: secret
          objectAlias: AZURE_TRANSLATOR_ENDPOINT
        - |
          objectName: azure-translator-key
          objectType: secret
          objectAlias: AZURE_TRANSLATOR_KEY
        - |
          objectName: azure-translator-region
          objectType: secret
          objectAlias: AZURE_TRANSLATOR_REGION
        - |
          objectName: azure-speech-key
          objectType: secret
          objectAlias: AZURE_SPEECH_KEY
        - |
          objectName: azure-speech-region
          objectType: secret
          objectAlias: AZURE_SPEECH_REGION
        - |
          objectName: azure-storage-connection-string
          objectType: secret
          objectAlias: AZURE_STORAGE_CONNECTION_STRING
        - |
          objectName: node-env
          objectType: secret
          objectAlias: NODE_ENV
        - |
          objectName: port
          objectType: secret
          objectAlias: PORT
    # Get this value from: az account show --query tenantId -o tsv
    tenantId: "YOUR-AZURE-TENANT-ID"
  secretObjects:
  - secretName: rag-app-secrets
    type: Opaque
    data:
    - objectName: GOOGLE_CLIENT_EMAIL
      key: GOOGLE_CLIENT_EMAIL
    - objectName: GOOGLE_PRIVATE_KEY
      key: GOOGLE_PRIVATE_KEY
    - objectName: GOOGLE_PROJECT_ID
      key: GOOGLE_PROJECT_ID
    - objectName: GOOGLE_CLIENT_ID
      key: GOOGLE_CLIENT_ID
    - objectName: GOOGLE_PRIVATE_KEY_ID
      key: GOOGLE_PRIVATE_KEY_ID
    - objectName: GOOGLE_DRIVE_FOLDER_ID
      key: GOOGLE_DRIVE_FOLDER_ID
    - objectName: AZURE_OPENAI_API_KEY
      key: AZURE_OPENAI_API_KEY
    - objectName: AZURE_OPENAI_ENDPOINT
      key: AZURE_OPENAI_ENDPOINT
    - objectName: AZURE_OPENAI_DEPLOYMENT_NAME
      key: AZURE_OPENAI_DEPLOYMENT_NAME
    - objectName: AZURE_OPENAI_EMBEDDING_DEPLOYMENT
      key: AZURE_OPENAI_EMBEDDING_DEPLOYMENT
    - objectName: AZURE_SEARCH_ENDPOINT
      key: AZURE_SEARCH_ENDPOINT
    - objectName: AZURE_SEARCH_API_KEY
      key: AZURE_SEARCH_API_KEY
    - objectName: AZURE_SEARCH_INDEX_NAME
      key: AZURE_SEARCH_INDEX_NAME
    - objectName: GEMINI_API_KEY
      key: GEMINI_API_KEY
    - objectName: GEMINI_MODEL
      key: GEMINI_MODEL
    - objectName: AZURE_DOC_INTELLIGENCE_ENDPOINT
      key: AZURE_DOC_INTELLIGENCE_ENDPOINT
    - objectName: AZURE_DOC_INTELLIGENCE_KEY
      key: AZURE_DOC_INTELLIGENCE_KEY
    - objectName: AZURE_TRANSLATOR_ENDPOINT
      key: AZURE_TRANSLATOR_ENDPOINT
    - objectName: AZURE_TRANSLATOR_KEY
      key: AZURE_TRANSLATOR_KEY
    - objectName: AZURE_TRANSLATOR_REGION
      key: AZURE_TRANSLATOR_REGION
    - objectName: AZURE_SPEECH_KEY
      key: AZURE_SPEECH_KEY
    - objectName: AZURE_SPEECH_REGION
      key: AZURE_SPEECH_REGION
    - objectName: AZURE_STORAGE_CONNECTION_STRING
      key: AZURE_STORAGE_CONNECTION_STRING
    - objectName: NODE_ENV
      key: NODE_ENV
    - objectName: PORT
      key: PORT